name: publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-rfc:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install kramdown-rfc
        run: gem install kramdown-rfc
      - name: Install xml2rfc
        run: pip install xml2rfc

      - name: Convert working version of Authz API 1.0 to rfc xml
        run: kramdown-rfc2629 api/authorization-api-1_0.md > api/authorization-api-1_0.xml
      - name: Render Authz API 1.0 HTML
        run: xml2rfc api/authorization-api-1_0.xml --html -o authorization-api-1_0.html
      - name: Render Index HTML (this is the current working draft of the spec)
        run: xml2rfc api/authorization-api-1_0.xml --html -o index.html
      - name: Render Authz API 1.0 Text
        run: xml2rfc api/authorization-api-1_0.xml --text
      - name: Upload Authz API 1.0 artifact
        uses: actions/upload-artifact@v4
        with:
          name: authorization-api-1_0
          path: |
            index.html
            authorization-api-1_0.html
            api/authorization-api-1_0.xml
      
      - name: Convert Authz Design Patterns to rfc xml
        run: kramdown-rfc2629 patterns/AuthorizationDesignPatterns.md > patterns/AuthorizationDesignPatterns.xml
      - name: Render Authz Design Patterns HTML
        run: xml2rfc patterns/AuthorizationDesignPatterns.xml --html -o patterns.html
      - name: Render Authz Design Patterns Text
        run: xml2rfc patterns/AuthorizationDesignPatterns.xml --text
      - name: Upload Authz Design Patterns artifact
        uses: actions/upload-artifact@v4
        with:
          name: patterns-doc
          path: |
            patterns.html
            patterns/AuthorizationDesignPatterns.xml

      - name: Upload Authz API 1.0 original submission artifact (version 0_0)
        uses: actions/upload-artifact@v4
        with:
          name: authorization-api-0_0
          path: |
            archive/authorization-api-0_0.html

  publish-to-pages:
    if: github.ref == 'refs/heads/main'
    needs: [build-rfc]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: authorization-api-*
          path: .
          merge-multiple: true
      - name: Download artifact - pattern document
        uses: actions/download-artifact@v4
        with:
          name: patterns-doc
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
